version: '2.4'
services:
  new_1:
    image: cappta/novo
    platform: linux
    expose:
      - "80"

  new_2:
    image: cappta/novo
    platform: linux
    expose:
      - "80"

  legacy:
    image: cappta/legado
    platform: windows
    expose:
      - "80"

  proxy:
    image: cappta/proxy
    platform: linux
    ports:
      - "80:80"
    links:
      - "new_1"
      - "new_2"
      - "legacy"
    depends_on:
      - new_1
      - new_2
      - legacy