version: '2.4'
services:
  new:
    image: cappta/novo
    platform: linux
    scale: 2
    expose:
      - "80"

  legacy:
    image: cappta/legado
    platform: windows
    expose:
      - "80"

  proxy:
    image: cappta/proxy
    platform: linux
    ports:
      - "80:80"
    links:
      - "new"
      - "legacy"
    depends_on:
      - new
      - legacy